name: gh-pages

on:
  push:
    branches:
      - doxygen-docs

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: build-docs
        uses: mattnotmitt/doxygen-action@v1

      - name: deploy-docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
