name: unit-tests
on: [push, pull_request]
jobs:
  unit-tests-linux:
    runs-on: ubuntu-latest
    steps:
      - name: install requirements
        run: |
         sudo apt-get -qq update
         sudo apt-get install -y build-essential cmake
      - name: install libcheck
        run: |
         git clone https://github.com/libcheck/check.git --branch 0.15.2 && cd check
         autoreconf --install
         ./configure
         make && sudo make install
         sudo ldconfig
         cd .. && rm -rf check
      - uses: actions/checkout@v2
      - name: versions info
        run: |
          cmake --version
      - name: create configs
        run: mkdir build && cd build && cmake ..
      - name: make
        run: make
        working-directory: ./build
      - name: unit tests
        run: make test
        working-directory: ./build

  unit-tests-macos:
    runs-on: macos-latest
    steps:
      - name: install requirements
        run: brew install pkg-config check
      - uses: actions/checkout@v2
      - name: versions info
        run: |
         cmake --version
         brew info check
         brew info pkg-config
      - name: create configs
        run: mkdir build && cd build && cmake ..
      - name: make
        run: make
        working-directory: ./build
      - name: unit tests
        run: make test
        working-directory: ./build